### ISSUE TITLE
Create Bank Transactions API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#11]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Bank Transactions API: 
- https://thenewboston.com/bank-api/bank-transactions

**Comment by nishp77** [comment]
@Mirch  want to ask if you have submitted the Accounts API PR into the repo?

**Comment by nishp77** [comment]
Working on it
