### ISSUE TITLE
Create Banks API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#12]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Banks API: 
- https://thenewboston.com/bank-api/banks
- https://thenewboston.com/primary-validator-api/banks

**Comment by xmac11** [comment]
Hey, I'll work on this one, if nobody is!

**Comment by itsnikhil** [comment]
@xmac11 what is your account number?

**Comment by xmac11** [comment]
@itsnikhil 
8ff92d181cb09f18ef2a1b03badb5bf4a8962f7e5bb55641d0358d99bf7d5655
