### ISSUE TITLE
Create Blocks API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#13]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Blocks API: 
- https://thenewboston.com/bank-api/blocks
- https://thenewboston.com/primary-validator-api/bank-blocks

**Comment by alfkonee** [comment]
Can this please be assigned to me??

**Comment by alfkonee** [comment]
Sorry I see its already been assigned
