### ISSUE TITLE
Create the Connection Requests API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#17]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Connection Requests API: 
- https://thenewboston.com/bank-api/connection-requests
- https://thenewboston.com/primary-validator-api/connection-requests

**Comment by arjunraghurama** [comment]
Will give it a try

**Comment by alfkonee** [comment]
@arjunraghurama Please any progress here???

**Comment by arjunraghurama** [comment]
@alfkonee Working on it!
