### ISSUE TITLE
Create the Confirmation Services API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#18]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Confirmation Servicesonfig API: 
- https://thenewboston.com/bank-api/validator-confirmation-services
- https://thenewboston.com/confirmation-validator-api/bank-confirmation-services

**Comment by nishp77** [comment]
Working on it

**Comment by Mirch** [comment]
@nishp77 how's it going?

**Comment by nishp77** [comment]
@Mirch sorry for the delay but i will post it at the end of the day

**Comment by Mirch** [comment]
> @Mirch sorry for the delay but i will post it at the end of the day

No worries, I was just checking in.
