### ISSUE TITLE
Create the Upgrade Notice API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#19]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Upgrade Notice API: 
- https://thenewboston.com/bank-api/upgrade-notice
- https://thenewboston.com/confirmation-validator-api/upgrade-request

**Comment by joshman1019** [comment]
I'll start working on this one :)

**Comment by joshman1019** [comment]
Upgrade Notices are done. I'm going to do the Upgrade Requests as a separate PR.

**Comment by Mirch** [comment]
Alright, I'll create another issue for that. Should have done it from the beginning.
