### ISSUE TITLE
Create the Validators API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#20]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Validators API: 
- https://thenewboston.com/bank-api/validators
- https://thenewboston.com/primary-validator-api/validators

**Comment by DylanGTech** [comment]
Hello! I can do this one if nobody else is.
Should I worry about the services being renamed first (as outlined in the current project) before doing this?

**Comment by itsnikhil** [comment]
@DylanGTech what is your account number?

**Comment by DylanGTech** [comment]
> @DylanGTech what is your account number?

Here is my account number:
5c7c896d4af6228a50ae180eb41e72c7ab276fa31de5de9081078113fb6e1fcf
