### ISSUE TITLE
Create the Primary Validator Updated API

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#21]
Follow the [Accounts API PR](https://github.com/thenewboston-developers/dotnetcore-sdk/pull/10) to develop a wrapper around the Primary Validator Updated API: 
- https://thenewboston.com/confirmation-validator-api/primary-validator-updated

**Comment by joshman1019** [comment]
Looks like this is the last one. I'll work on it.
