### ISSUE TITLE
Possible NullReferenceException in API Models

### ISSUE THREAD

**Issue by joshman1019** [thenewboston-developers/dotnetcore-sdk#22]
### I am doing a sweep through as much of the code as possible, and have identified a couple of lines that may result in eventual NullReferenceExceptions in the BankService model during the deserialization process.  

https://github.com/thenewboston-developers/dotnetcore-sdk/blob/44f9ff20f4e1a83feb97ff4c7906956fbe2ecda1/src/Thenewboston/Bank/Api/BankService.cs#L26

https://github.com/thenewboston-developers/dotnetcore-sdk/blob/44f9ff20f4e1a83feb97ff4c7906956fbe2ecda1/src/Thenewboston/Bank/Api/BankService.cs#L45

I will submit a pull request with suggested fixes.

**Comment by joshman1019** [comment]
I have located a few more instances of the same issue that I am adding to the issue: 

https://github.com/thenewboston-developers/dotnetcore-sdk/blob/44f9ff20f4e1a83feb97ff4c7906956fbe2ecda1/src/Thenewboston/Validator/Api/ValidatorService.cs#L22

https://github.com/thenewboston-developers/dotnetcore-sdk/blob/44f9ff20f4e1a83feb97ff4c7906956fbe2ecda1/src/Thenewboston/Validator/Api/ValidatorService.cs#L38

https://github.com/thenewboston-developers/dotnetcore-sdk/blob/44f9ff20f4e1a83feb97ff4c7906956fbe2ecda1/src/Thenewboston/Validator/Api/ValidatorService.cs#L54

**Comment by Mirch** [comment]
Great work! You're right!

**Comment by joshman1019** [comment]
Honored to help! Thank you guys for giving us the opportunity.
