### ISSUE TITLE
Create specific exceptions for API calls

### ISSUE THREAD

**Issue by xmac11** [thenewboston-developers/dotnetcore-sdk#30]
- Currently each service class has a couple _TODOs_ for creating a specific exception for API calls.

- Despite this being briefly mentioned on Slack a couple of days ago, I think it's worth elaborating a bit on this and re-thinking it one laste time.
So I'd like to point out the code duplication that currently exists in Service classes, which makes methods quite longer, hides the business logic behind error-handling of API calls and, ultimately, requires us tracking every Service class to make the above change. 
I think a generic wrapper would be the best option if it's something easy to implement. 
[This is what the Kotlin-SDK devs are currently trying out.](https://github.com/thenewboston-developers/Kotlin-SDK/pull/43#discussion_r523438683)

**Comment by joshman1019** [comment]
I have been waiting for other developers to jump in for a few days now to see how it will work out once things start to grow a bit. I honestly feel like we could probably make this codebase smaller and easier to maintain with a different structure/layout. I also believe that there needs to be a focus on the single-responsibility principle since a lot of our service methods are serializing to JSON, Making an API call, receiving a response, and deserializing. That is a pretty large surface area if a bug arises.

**Comment by Mirch** [comment]
Let's use this issue as a way to discuss possible implementations and usage examples. I like the Kotlin example. Do you guys have any suggestions?

**Comment by xmac11** [comment]
I must say that architecting solutions is way way way out of my league, however I made an initial attempt (not complete though) in case this leads us somewhere, or gives you guys any better ideas. (Not sure if I'm following C# best practices either :grin:).

So I create a new class,[ NetworkClient.cs](https://gist.github.com/xmac11/8756a1ef9039284a1fb5b56611b94b64),  to hold the repeating code. This results in the Service classes becoming a simple forwarder, for example the `ConnectedBanksService` becomes:

```
public class ConnectedBanksService : IConnectedBanksService
    {
        private readonly INetworkClient _networkClient;

        public ConnectedBanksService(INetworkClient networkClient)
        {
            _networkClient = networkClient;
        }

        public async Task<ResponseModel> GetBanksAsync()
        {
            return await _networkClient.makeApiFetchCall<ResponseModel>("/banks");
        }

        public async Task<BankResponseModel> UpdateBankAsync(string nodeIdentifier, RequestModel payload)
        {
            return await _networkClient.makeApiPatchCall<BankResponseModel>(nodeIdentifier, payload);
        }
    }

```

**Comment by joshman1019** [comment]
I have also created an HTTP Message response converter that will accept any type. It will need a bit more polish also, and maybe a different name, but I think it may work to replace quite a bit of code in our service classes. 
~~~

    internal sealed class HttpResponseConverter<T>
    {
        private readonly HttpResponseMessage m_Message;

        public HttpResponseConverter(HttpResponseMessage message)
        {
            if(message == null)
            {
                // TODO: Some type of exception
                throw new Exception(); 
            }

            m_Message = message;
        }

        public async T GetResult()
        {
            if (!m_Message.IsSuccessStatusCode)
            {
                // TODO: Some type of exception
                throw new Exception(); 
            }

            var stringResult = await m_Message.Content.ReadAsStringAsync(); 

            if(string.IsNullOrEmpty(stringResult))
            {
                // TODO: Some type of exception
                throw new Exception(); 
            }

            return JsonConvert.DeserializeObject<T>(stringResult); 
        }
    }

~~~

Used in the BankService class

~~~

        public async Task<BankAccount> UpdateAccountAsync(string accountNumber, AccountRequestModel account)
        {
            var jsonAccount = JsonConvert.SerializeObject(account);
            var httpContent = new StringContent(jsonAccount, Encoding.UTF8, "application/json");

            var response = await _requestSender.PatchAsync($"/accounts/{accountNumber}", httpContent);

            var result = new HttpResponseConverter<BankAccount>(response);
            return result.GetResult(); 
        }

~~~

**Comment by joshman1019** [comment]
Oh I just realized I used my own naming conventions here... again it is a sample, but m_Name is my convention for private members. That way I can always find my members with IntelliSense with "m_". Public members are always "M_Name".   I also follow all async methods with _ASYNC so that they are more identifiable. Sooo if you ever see those just know I'm a creature of habit lol.

**Comment by Mirch** [comment]
Thanks for the input and sorry for being late on this :) I'll put together something regarding the requests and be back with a PR for review. Afterwards, we can talk more about exceptions.
