### ISSUE TITLE
Rename ResponseModel

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#35]
Rename `ResponseModel` ([here](https://github.com/thenewboston-developers/dotnetcore-sdk/blob/develop/src/Thenewboston/Common/Api/Models/ResponseModel.cs)) to `PaginatedResponseModel`.

**Comment by arjunraghurama** [comment]
Would like to work on this!

**Comment by itsnikhil** [comment]
@arjunraghurama what is your account number?

**Comment by arjunraghurama** [comment]
@itsnikhil 

I've sent my account number in Slack

**Comment by itsnikhil** [comment]
Hi @arjunraghurama I cannot find your account number on slack. If you are on dotnet slack group, I have just texted a message there. Please DM your account number or just reply in thread!
