### ISSUE TITLE
Build NuGet package

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#6]
A NuGet package should be created and pushed whenever a pull request is merge into `main`. 

The task related to this issue is to create a Github Actions workflow that:
- builds the project
- builds the NuGet package
- pushes the NuGet package
- creates a release for the SDK on this repository

Dependencies: 
- a `develop` branch where PRs are merged when approved (`main` should be reserved for releases)
- an account for thenewboston on nuget.org

**Comment by arjunraghurama** [comment]
Hey. In Visual Studio under build tab we can Pack the project which will result in NuGet package. If this ticket is regarding the same, I can give a try
