### ISSUE TITLE
Handle Timeout Exception in SImpleHttpRequestSender

### ISSUE THREAD

**Issue by joshman1019** [thenewboston-developers/dotnetcore-sdk#63]
During one of my tests of the latest build, I attempted to connect to a validator that was offline. I noticed that the timeout exception wasn't handled. I wasn't sure if we were going to expose SimpleHttpRequestSender as public, or if we were going to expose the interface only (using SimpleHttpRequestSender for testing only). If it will be public we may want to handle timeout exceptions.

**Comment by alfkonee** [comment]
Isn't this related to #30 ?? as an effort to create unified Exceptions??

**Comment by joshman1019** [comment]
In a way, but the exception isn't handled currently. In the other service models we have placed generic exceptions.

**Comment by Mirch** [comment]
Let's start slowly, then, with handling this one :)

**Comment by joshman1019** [comment]
I will try to work on this one today once the day job is behind me. It's a strange exception and I think I may have it written down somewhere already 😂
