### ISSUE TITLE
Create Validator app layer

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#78]
Follow the example in #79 to implement the app layer that wraps all the Validator/Primary validator endpoints.

For endpoints that don't make sense to implement (and those that return HttpResponseMessage), you can skip them.

**Comment by nishp77** [comment]
working on it

**Comment by nishp77** [comment]
@Mirch I'm not understanding the app layer, is it that layer should contain what a validator could do?

**Comment by Mirch** [comment]
> @Mirch I'm not understanding the app layer, is it that layer should contain what a validator could do?

It's what people can do with a validator - not banks or other validators, but any 3rd party using the API. Also, to answer the question in the PR, you are right to not include the bank blocks. Should I review the rest of it, or do you have any other changes to make?

**Comment by nishp77** [comment]
You could review it as I'm done with it
