### ISSUE TITLE
Remove unusable endpoints

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#80]
Some endpoints contained in the documentation are only used for validator-bank communication, so using them from an application that calls upon the SDK makes no sense (and it isn't possible, anyway). We should remove these endpoints from all layers.

Some of them are marked accordingly in the documentation (you can see a note like `Validator > Bank`), other are not. Most of them are POST/PATCH requests.

**Comment by tomijaga** [comment]
These are the endpoints I found for  **Validator > Bank** 
BankBlockServices
BankConfirmationServices
ConnectedBankService
ConnectionRequestServices
UpgradeRequestService

Is this all or are there still some I am missing?

**Comment by Mirch** [comment]
I believe so, but I'm checking with the team leads of the other SDKs first. Would you like to work on this issue once we get all the information?

**Comment by tomijaga** [comment]
Yes, I would.

**Comment by Mirch** [comment]
Alright, I'll assign it to you. Just give me a day or two so I can come back with final information.

**Comment by Mirch** [comment]
Ok, I checked and I believe you are right, @tomijaga. You can remove those endpoints that you mentioned :)
